dist: bionic
language: java
jdk:
  - oraclejdk11


addons:
      sonarcloud:
        organization: "ehrwald"
        token:
          secure: "$SONAR_TOKEN"
script:
  - mvn jetty:run &
  - sleep 30s
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=
  - mvn test -B