dist: bionic
language: java
jdk:
  - oraclejdk11


addons:
      sonarcloud:
        organization: "ehrwald"
        token:
          secure: "$SONAR_TOKEN"
script:
  - mvn jetty:run &
  - mvn test -B