language: java

install: jetty:run
addons:
  sonarcloud:
    organization: "ehrwald"
    token:
      secure: "$SONAR_TOKEN"
jdk:
  - oraclejdk11

script:
        # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Ehrwald_petitfilrouge