dist: bionic
language: java
jdk:
  - oraclejdk11
cache:
  directories:
    - .autoconf
    - $HOME/.m2

addons:
      sonarcloud:
        organization: "Ehrwald"
        token:
          secure: "$SONAR_TOKEN"
script:
  - mvn install
  - mvn jetty:run &
  - sleep 30s
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=
  - mvn test -B
