dist: bionic

language: java
jdk:
  - oraclejdk11

jobs:
  include:
    - stage: préinstall
      addons:
       sonarcloud:
        organization: "ehrwald"
        token:
          secure: "$SONAR_TOKEN"
    script:
    - mvn jetty:run
    - stage: start test
    script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=
    - mvn test -B